# Generated by Django 6.0.5 on 2026-05-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_uz', models.TextField()),
                ('image_ru', models.TextField()),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['position'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.TextField()),
                ('name_uz', models.TextField()),
                ('image', models.TextField()),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['position'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'favorites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('items', models.TextField(default='[]')),
                ('service_ids', models.TextField(default='[]')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('status', models.TextField(default='pending')),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('phone', models.TextField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'phone_verifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_uz', models.TextField(blank=True, null=True)),
                ('name_ru', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('currency', models.TextField(default='UZS')),
                ('images', models.TextField(default='[]')),
                ('sizes', models.TextField(default='[]')),
                ('category_id', models.IntegerField()),
                ('category_name', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('in_stock', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
            ],
            options={
                'db_table': 'products',
                'ordering': ['position'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_uz', models.TextField(blank=True, null=True)),
                ('name_ru', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('time', models.TextField(blank=True, null=True)),
                ('time_uz', models.TextField(blank=True, null=True)),
                ('time_ru', models.TextField(blank=True, null=True)),
                ('possibilities', models.TextField(default='[]')),
                ('possibilities_uz', models.TextField(default='[]')),
                ('possibilities_ru', models.TextField(default='[]')),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('phone_hash', models.TextField(blank=True, null=True, unique=True)),
                ('auth_token', models.TextField(blank=True, null=True, unique=True)),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
